app/imap/__init__.py
from flask import Blueprint


imap_blueprint = Blueprint('imap', __name__, template_folder='templates')

from . import views

app/imap/views.py
from . import imap_blueprint as imap
from flask import redirect, render_template, request, session, url_for, send_file
from app.pagination import Pagination
from app.services import my_imap


@imap.route('/<string:mailbox>/page/<int:page>/', methods=['GET'])
@imap.route('/<string:mailbox>/', defaults={'page': 1}, methods=['GET'])
@imap.route('/', defaults={'mailbox': 'inbox', 'page': 1}, methods=['GET'])
def index(mailbox, page):
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    per_page = 20
    imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
    total, mail_list, mailboxes = imap_obj.messages_list(page, per_page, mailbox)
    pagination = Pagination(page, per_page, total)
    return render_template('imap/index.html', mail_list=mail_list, errors=imap_obj.errors, protocol='imap',
                           mailbox=mailbox, mailboxes=mailboxes, pagination=pagination)


@imap.route('/<string:mailbox>/mail/<int:uid>/', methods=['GET'])
def readmail(mailbox, uid):
    imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
    message = imap_obj.read_msg(mailbox, uid)
    return render_template('imap/readmail.html', mailbox=mailbox, message=message)


@imap.route('/<string:mailbox>/mark/seen/', methods=['GET', 'POST'])
def mark_seen(mailbox):
    if request.method == 'POST':
        imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
        imap_obj.mark_seen(request.form.getlist('mail_ids'), mailbox)
    return redirect(url_for('imap.index', mailbox=mailbox), 302)


@imap.route('/<string:mailbox>/mark/unseen/', methods=['GET', 'POST'])
def mark_unseen(mailbox):
    if request.method == 'POST':
        imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
        imap_obj.mark_unseen(request.form.getlist('mail_ids'), mailbox)
    return redirect(url_for('imap.index', mailbox=mailbox), 302)


@imap.route('/<string:mailbox>/mark/deleted/', methods=['GET', 'POST'])
def mark_deleted(mailbox):
    if request.method == 'POST':
        imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
        imap_obj.mark_deleted(request.form.getlist('mail_ids'), mailbox)
    return redirect(url_for('imap.index', mailbox=mailbox), 302)


@imap.route('/<string:mailbox>/download/<int:uid>/<string:filename>', methods=['GET'])
def download(mailbox, filename, uid):
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    imap_obj = my_imap.MyIMAP(session['mailbox'][0], session['mailbox'][1])
    file = imap_obj.download(mailbox, filename, uid)
    return send_file(file, attachment_filename=filename, as_attachment=True)

app/imap/templates/imap/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='style/style.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='style/fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <div class="brand">
          <a href="{{url_for('imap.index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('imap.index')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content" protocol="{{protocol}}" mailbox="{{mailbox}}" id="content">
        {% if errors%}
          <div class="errors">
            {%for error in errors%}
              <div class="error">{{error}}</div>
            {%endfor%}
          </div>
        {%endif%}

        {% if 'Notify' in session%}
          <div class="notifications">
            {%for notification in session.pop('Notify')%}
              <div class="notification">{{notification}}</div>
            {%endfor%}
          </div>
        {%endif%}

        <div class="boxes_menu">
          <a class="new_msg" href="{{url_for('smtp.new_mail')}}">
            <i class="fas fa-plus">Написать</i>
          </a>
          <div class="boxes">
            {%for key, box in mailboxes.items()%}
              <a class="box" href="{{url_for('imap.index', mailbox=key)}}">
                {{box[0]}}
              </a>
            {%endfor%}
          </div>
        </div>
        <div class="mailbox">
          <form class="" action="" method="post">
            <div class="control-panel">
              <div class="mail-check-block">
                <input class="mail-check" type="checkbox" name="" value="" id="m">
                <label class="answer-text" for="m", title="Выделить все"></label>
              </div>
              <div class="control-buttons">
                <i class="control-button fas fa-trash disabled" title="Удалить" id="deleted"></i>
                <i class="control-button fas fa-envelope-open disabled" title="Отметить как прочитанное" id="seen"></i>
                <i class="control-button fas fa-envelope disabled" title="Отметить как непрочитанное" id="unseen"></i>
              </div>
              <div class="">
                <div class=pagination>
                  {% if pagination%}
                      {% for page in pagination.iter_pages() %}
                        {% if page %}
                            {% if page != pagination.page %}
                              <a class="other_page" href="{{url_for('imap.index', mailbox=mailbox, page=page)}}">{{page}}</a>
                            {% else %}
                              <span class="curr_page">{{ page }}</span>
                            {% endif %}
                        {% else %}
                            <span class=ellipsis>…</span>
                        {% endif %}
                      {% endfor %}
                  {%endif%}
                </div>
              </div>
            </div>
            <div class="mails">
              {%for mail in mail_list%}
                {%if mail['unseen']%}
                  <a href="{{url_for('imap.readmail', mailbox=mailbox, uid=mail['uid'])}}" class="mail active">
                {%else%}
                  <a href="{{url_for('imap.readmail', mailbox=mailbox, uid=mail['uid'])}}" class="mail">
                {%endif%}
                    <div class="mail-check-block">
                      <input class="mail-check reg_mail" type="checkbox" name="mail_ids" value="{{mail['uid']}}" id="{{mail['uid']}}">
                      <label class="answer-text" for="{{mail['uid']}}"></label>
                    </div>
                    <div class="from">
                      {%if mailbox == 'sent'%}
                        {{mail['to']}}
                      {%else%}
                        {{mail['from']}}
                      {%endif%}
                    </div>
                    <div class="topic">{{mail['subject']}}</div>
                </a>
              {%endfor%}
            </div>
          </form>
        </div>

        <div class="plug">

        </div>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="{{url_for('auth.logout')}}">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='javascript/jquery-3.3.1.min.js')}}></script>
  	<script type="text/javascript" src={{url_for('static', filename='javascript/script.js')}}></script>
  </body>
</html>

app/imap/templates/imap/mail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='mail.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="my_header">
        <div class="brand">
          <a href="{{url_for('index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="{{url_for('index', protocol='pop3')}}" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('index', protocol='imap')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content">
        <div class="mail">
          <div class="topic">
            <h2>
              {%if message['Subject']%}
                {{message['Subject']}}
              {%else%}
                (без темы)
              {%endif%}
            </h2>
          </div>
          <div class="from">
            <span>Отправитель: </span>
            {{message['From']}}
          </div>

          <div class="to">
            <span>Получатель: </span>
            {{message['To']}}
          </div>

          <br><br>

          <div class="msg">
            {{message['Content']|safe|urlize(40)}}
          </div>
        </div>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="/logout/">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='jquery-3.3.1.min.js')}}></script>
  </body>
</html>

app/imap/templates/imap/readmail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='style/readmail.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='style/fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="my_header">
        <div class="brand">
          <a href="{{url_for('index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="{{url_for('index', protocol='pop3')}}" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('imap.index', protocol='imap')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content">
        <div class="mail">
          <div class="topic">
            <h2>
              {%if message['Subject']%}
                {{message['Subject']}}
              {%else%}
                (без темы)
              {%endif%}
            </h2>
          </div>
          <div class="from">
            <span>Отправитель: </span>
            {{message['From']}}
          </div>

          <div class="to">
            <span>Получатель: </span>
            {{message['To']}}
          </div>
          <br>

          {%if message['Attachments']%}
            <div class="attachments">
              {%for attach in message['Attachments']%}
                <a href="{{url_for('imap.download', mailbox=mailbox, uid=message['uid'], filename=attach)}}" class="attachment">
                  {{attach}}
                </a>
              {%endfor%}
            </div>
          {%endif%}

          <br>

          <div class="msg">
            {{message['Content']|safe|urlize(40)}}
          </div>
        </div>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="/logout/">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='javascript/jquery-3.3.1.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='javascript/script.js')}}></script>
  </body>
</html>