app/smtp/forms/new_mail.py
from flask_wtf import FlaskForm
from wtforms import MultipleFileField, TextAreaField, validators, StringField, SubmitField


class NewMail(FlaskForm):
    to = StringField(validators=[validators.DataRequired(), validators.Email(message='Неверный адрес почты!')],
                     render_kw={'placeholder': 'Введите email получателя', 'required': '',
                                'multiple': '', 'type': 'email'})
    subject = StringField(validators=[validators.Optional()], render_kw={'placeholder': 'Введите тему сообщения'})
    mail_body = TextAreaField(validators=[validators.Optional()], render_kw={'placeholder': 'Туть Ваше сообщенько...',
                                                                             'rows': '20', 'cols': '80'})
    attachments = MultipleFileField(render_kw={'data-multiple-caption': '{count} файла выбрано!',
                                               'class': 'file', 'multiple': ''})
    submit = SubmitField(label='Отправить', render_kw={'class': 'submit'})

app/smtp/__init__.py
from flask import Blueprint

smtp_blueprint = Blueprint('smtp', __name__, template_folder='templates')

from . import views

app/smtp/views.py
from werkzeug.datastructures import CombinedMultiDict
from . import smtp_blueprint as smtp
from flask import redirect, render_template, request, session, url_for
from app.smtp.forms.new_mail import NewMail
from app.services import my_smtp


@smtp.route('/new/', methods=['GET', 'POST'])
def new_mail():
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    new_mail_form = NewMail(CombinedMultiDict((request.files, request.form)))
    smtp_obj = my_smtp.MySMTP(session['mailbox'][0], session['mailbox'][1])
    if request.method == 'POST':
        if smtp_obj.send(new_mail_form):
            session['Notify'] = ('Сообщение отправлено!', )
            return redirect(url_for('imap.index', mailbox='sent'), 302)
    return render_template('smtp/newmail.html', new_mail_form=new_mail_form, errors=smtp_obj.errors)

app/smtp/templates/smtp/newmail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='style/newmail.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='style/fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="my_header">
        <div class="brand">
          <a href="{{url_for('index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="{{url_for('index', protocol='pop3')}}" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('imap.index', protocol='imap')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content">
        {% if errors%}
          <div class="errors">
            {%for error in errors%}
              <div class="error">{{error}}</div>
            {%endfor%}
          </div>
        {%endif%}

        {% if 'Notify' in session%}
          <div class="notifications">
            {%for notification in session.pop('Notify')%}
              <div class="notification">{{notification}}</div>
            {%endfor%}
          </div>
        {%endif%}

        <form class="" enctype="multipart/form-data" action="{{url_for('smtp.new_mail')}}" method="post">
          <div class="newmail">
            <div class="to">
              {{new_mail_form['to']}}
            </div>
            <div class="theme">
              {{new_mail_form['subject']}}
            </div>
            <div class="msg_content">
              {{new_mail_form['mail_body']}}
            </div>
            <div class="submit-block">
              {{new_mail_form['attachments']}}
              <label for="attachments">
                <span><i class="fas fa-download"></i>Выберите файлы...</span>
              </label>
              {{new_mail_form['submit']}}
            </div>
          </div>
        </form>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="{{url_for('auth.logout')}}">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='javascript/jquery-3.3.1.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='javascript/script.js')}}></script>
  </body>
</html>