app/pop3/__init__.py
from flask import Blueprint


pop3_blueprint = Blueprint('pop3', __name__, template_folder='templates')

from . import views

app/pop3/views.py
from . import pop3_blueprint as pop3
from flask import redirect, render_template, request, session, url_for, send_file
from app.pagination import Pagination
from app.services import my_pop3


@pop3.route('/page/<int:page>/', methods=['GET'])
@pop3.route('/', defaults={'page': 1}, methods=['GET'])
def index(page):
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    per_page, mail_list, pagination = 20, [], None
    pop3_obj = my_pop3.MyPOP3(session['mailbox'][0], session['mailbox'][1])
    total, mail_list = pop3_obj.get_messages_list(page, per_page)
    pagination = Pagination(page, per_page, total)
    return render_template('pop3/index.html', mail_list=mail_list, errors=pop3_obj.errors, protocol='pop3',
                           pagination=pagination)


@pop3.route('/mail/<int:mid>/', methods=['GET'])
def readmail(mid):
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    pop3_obj = my_pop3.MyPOP3(session['mailbox'][0], session['mailbox'][1])
    message = pop3_obj.get_message(mid)
    return render_template('pop3/readmail.html', message=message, errors=pop3_obj.errors)


@pop3.route('/mark/deleted/', methods=['GET', 'POST'])
def mark_deleted():
    if request.method == 'POST':
        pop3_obj = my_pop3.MyPOP3(session['mailbox'][0], session['mailbox'][1])
        pop3_obj.delete_message(request.form.getlist('mail_ids'))
    return redirect(url_for('pop3.index'), 302)


@pop3.route('/download/<int:uid>/<string:filename>', methods=['GET'])
def download(filename, uid):
    if 'mailbox' not in session:
        return redirect('/auth/', code=302)
    pop3_obj = my_pop3.MyPOP3(session['mailbox'][0], session['mailbox'][1])
    file = pop3_obj.download(filename, uid)
    return send_file(file, attachment_filename=filename, as_attachment=True)

app/pop3/templates/pop3/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='style/style.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='style/fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <div class="brand">
          <a href="{{url_for('pop3.index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="{{url_for('pop3.index')}}" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('imap.index')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content" protocol="{{protocol}}" mailbox="{{mailbox}}" id="content">
        {% if errors%}
          <div class="errors">
            {%for error in errors%}
              <div class="error">{{error}}</div>
            {%endfor%}
          </div>
        {%endif%}

        {% if 'Notify' in session%}
          <div class="notifications">
            {%for notification in session.pop('Notify')%}
              <div class="notification">{{notification}}</div>
            {%endfor%}
          </div>
        {%endif%}

        <div class="boxes_menu">
          <a class="new_msg" href="{{url_for('smtp.new_mail')}}">
            <i class="fas fa-plus">Написать</i>
          </a>
        </div>
        <div class="mailbox">
          <form class="" action="" method="post">
            <div class="control-panel">
              <div class="mail-check-block">
                <input class="mail-check" type="checkbox" name="" value="" id="m">
                <label class="answer-text" for="m", title="Выделить все"></label>
              </div>
              <div class="control-buttons">
                <i class="control-button fas fa-trash disabled" title="Удалить" id="deleted"></i>
              </div>
              <div class="">
                <div class=pagination>
                  {% if pagination%}
                      {% for page in pagination.iter_pages() %}
                        {% if page %}
                            {% if page != pagination.page %}
                              <a class="other_page" href="{{url_for('pop3.index', page=page)}}">{{page}}</a>
                            {% else %}
                              <span class="curr_page">{{ page }}</span>
                            {% endif %}
                        {% else %}
                            <span class=ellipsis>…</span>
                        {% endif %}
                      {% endfor %}
                  {%endif%}
                </div>
              </div>
            </div>
            <div class="mails">
              {%for mail in mail_list%}
                <a href="{{url_for('pop3.readmail', mid=mail['id'])}}" class="mail active">
                  <div class="mail-check-block">
                    <input class="mail-check reg_mail" type="checkbox" name="mail_ids" value="{{mail['id']}}" id="{{mail['id']}}">
                    <label class="answer-text" for="{{mail['id']}}"></label>
                  </div>
                  <div class="from">
                      {{mail['From']}}
                  </div>
                  <div class="topic">{{mail['Subject']}}</div>
                </a>
              {%endfor%}
            </div>
          </form>
        </div>

        <div class="plug">

        </div>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="{{url_for('auth.logout')}}">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='javascript/jquery-3.3.1.min.js')}}></script>
  	<script type="text/javascript" src={{url_for('static', filename='javascript/script.js')}}></script>
  </body>
</html>

app/pop3/templates/pop3/readmail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for('static', filename='style/readmail.css') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='style/fontawesome-free-5.12.0-web/css/all.min.css') }}>
    <link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
    <title>Почточка</title>
  </head>
  <body>
    <div class="wrapper">
      <header class="my_header">
        <div class="brand">
          <a href="{{url_for('pop3.index')}}" class="link"><i class="fas fa-envelope-open-text text-logo"></i>Почточка</a>
        </div>
        <div class="navbar">
          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="{{url_for('pop3.index')}}" class="navbar-link link">POP3</a>
            </li>
            <li class="navbar-item">
              <a href="{{url_for('imap.index')}}" class="navbar-link link">IMAP</a>
            </li>
          </ul>
        </div>
      </header>

      <div class="content">
        {% if errors%}
          <div class="errors">
            {%for error in errors%}
              <div class="error">{{error}}</div>
            {%endfor%}
          </div>
        {%endif%}
        <div class="mail">
          <div class="topic">
            <h2>
              {%if message['Subject']%}
                {{message['Subject']}}
              {%else%}
                (без темы)
              {%endif%}
            </h2>
          </div>
          <div class="from">
            <span>Отправитель: </span>
            {{message['From']}}
          </div>

          <div class="to">
            <span>Получатель: </span>
            {{message['To']}}
          </div>
          <br>

          {%if message['Attachments']%}
            <div class="attachments">
              {%for attach in message['Attachments']%}
                <a href="{{url_for('pop3.download', uid=message['id'], filename=attach)}}" class="attachment">
                  {{attach}}
                </a>
              {%endfor%}
            </div>
          {%endif%}

          <br>

          <div class="msg">
            {{message['Content']|safe|urlize(40)}}
          </div>
        </div>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <div class="signs">
            <a href="/logout/">
              <p class="sign-item sign-head"><i class="fas fa-door-open text-logo"></i></p>
              <p class="sign-item">выход</p>
            </a>
          </div>

          <div class="social">
            <ul>
              <li class="social-item">
                <a href="https://vk.com/muffin3" class="social-link">
                  <i class="fab fa-vk"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://github.com/Muffin3" class="social-link">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="social-item">
                <a href="https://t.me/Muffin3" class="social-link">
                  <i class="fab fa-telegram-plane"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>

    <script type="text/javascript" src={{url_for('static', filename='javascript/jquery-3.3.1.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='javascript/script.js')}}></script>
  </body>
</html>